from players import PlayerController as PC
def main():
	print 'Starting Rock-Paper-Scissors\n'
	game = PC()
	# game.play('rock')
	# game.play('paper')
	# game.play('paper')
	# game.play('scissors')
	# game.play('rock')
	# game.play('rock')
	# game.play('rock')
	# game.play('scissors')
	game.auto_play(3)
	game.auto_play(3)
	game.auto_play(1)
	game.auto_play(1)
	game.auto_play(1)
	game.auto_play(1)
	game.auto_play(1)
	game.auto_play(3)
	game.auto_play(3)
	game.auto_play(1)
	game.auto_play(1)
	game.auto_play(1)
	game.auto_play(2)
	game.auto_play(2)
	game.auto_play(3)
	game.auto_play(3)
	game.auto_play(1)
	game.auto_play(1)
	game.auto_play(2)
	game.auto_play(2)
	game.auto_play(3)
	game.auto_play(3)
	game.auto_play(4)
	game.auto_play(4)
	#game.play('rock')
	#pc.get_result()
	
if __name__=='__main__':
	main()